services:
  web:
    image: mon_web
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/www
    networks:
      - dmz_net

  mariadb:
    image: mariadb:11.1
    env_file:
      - mariadb/root.env
      - mariadb/db.env
    volumes:
      #- ./db_data:/var/lib/mysql # persistance des données
      - ./mariadb/woodytoys.sql:/docker-entrypoint-initdb.d/woodytoys.sql
    networks:
      - db_net

  php:
    image: mon_php
    env_file:
      - mariadb/db.env
    volumes:
      - ./www:/var/www/html/www
    networks:
      - dmz_net
      - db_net

networks:
  dmz_net:
  db_net:
