services:
  web:
    image: mon_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html/www
      - ./web/nginx:/etc/nginx
      - ./web/certbot/conf:/etc/letsencrypt # certificats
      - ./web/certbot/log:/var/log/letsencrypt # challenge ACME
      - ./web/certificate/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./web/certificate/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - dmz_net

  mariadb:
    image: mariadb:11.1
    env_file:
      - mariadb/root.env
      - mariadb/db.env
    volumes:
      - ./mariadb/woodytoys.sql:/docker-entrypoint-initdb.d/woodytoys.sql
      - ./mariadb/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
      - mariadb_data:/var/lib/mysql
    networks:
      - db_net

  php:
    image: mon_php
    env_file:
      - mariadb/db.env
    volumes:
      - ./www:/var/www/html/www
    networks:
      - dmz_net
      - db_net

networks:
  dmz_net:
  db_net:

volumes:
  mariadb_data:
