version: "3.9"

services:
  db:
    build: database
    container_name: tp10_db
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    networks:
      - db_net

  misc:
    build: api
    container_name: tp10_misc
    working_dir: /app
    command: python misc.py
    networks:
      - dmz_net
      - db_net

  order:
    build: api
    container_name: tp10_order
    working_dir: /app
    command: python order.py
    networks:
      - dmz_net
      - db_net

  product:
    build: api
    container_name: tp10_product
    working_dir: /app
    command: python product.py
    networks:
      - dmz_net
      - db_net

  front:
    build: front
    container_name: tp10_front
    networks:
      - dmz_net

  reverse:
    build: reverse-proxy
    container_name: tp10_reverse
    ports:
      - "8080:80/tcp"
    depends_on:
      - front
      - misc
      - order
      - product
    networks:
      - dmz_net

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    container_name: tp10_redis
    networks:
      - db_net

networks:
  dmz_net:
  db_net:
