FROM nginx:stable-alpine

RUN apt update && apt install curl && apt install -y certbot python3-certbot-nginx && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/www/html/www
RUN mkdir -p /etc/ssl/certs
RUN mkdir -p /etc/ssl/private
RUN mkdir -p /etc/nginx/conf.d/
RUN mkdir -p /etc/nginx/sites-enabled/
