FROM nginx:stable

RUN apt update && apt install -y certbot python3-certbot-nginx && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/www/html/www
RUN mkdir -p /etc/ssl/certs
RUN mkdir -p /etc/ssl/private
